// <auto-generated />
using System;
using HotelAdoNet;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HotelAdoNet.Migrations
{
    [DbContext(typeof(MeuContexto))]
    [Migration("20221114205737_FotoQuartos_Reservas")]
    partial class FotoQuartos_Reservas
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("HotelAdoNet.FotoQuarto", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<byte[]>("Imagem")
                        .HasColumnType("varbinary(max)");

                    b.HasKey("id");

                    b.ToTable("FotosQuartos");
                });

            modelBuilder.Entity("HotelAdoNet.Quarto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("AC")
                        .HasColumnType("bit");

                    b.Property<int>("Area")
                        .HasColumnType("int");

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FotoId")
                        .HasColumnType("int");

                    b.Property<int?>("FotoQuartoid")
                        .HasColumnType("int");

                    b.Property<int>("Numero")
                        .HasColumnType("int");

                    b.Property<int>("Piso")
                        .HasColumnType("int");

                    b.Property<int>("ReservaId")
                        .HasColumnType("int");

                    b.Property<int>("TipologiaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FotoQuartoid");

                    b.HasIndex("ReservaId");

                    b.HasIndex("TipologiaId");

                    b.ToTable("Quartos");
                });

            modelBuilder.Entity("HotelAdoNet.Reserva", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DataFim")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Reservas");
                });

            modelBuilder.Entity("HotelAdoNet.Tipologia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Nome")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Tipologias");
                });

            modelBuilder.Entity("HotelAdoNet.Quarto", b =>
                {
                    b.HasOne("HotelAdoNet.FotoQuarto", "FotoQuarto")
                        .WithMany("Quartos")
                        .HasForeignKey("FotoQuartoid");

                    b.HasOne("HotelAdoNet.Reserva", "Reserva")
                        .WithMany("Quartos")
                        .HasForeignKey("ReservaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HotelAdoNet.Tipologia", "Tipologia")
                        .WithMany("Quartos")
                        .HasForeignKey("TipologiaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FotoQuarto");

                    b.Navigation("Reserva");

                    b.Navigation("Tipologia");
                });

            modelBuilder.Entity("HotelAdoNet.FotoQuarto", b =>
                {
                    b.Navigation("Quartos");
                });

            modelBuilder.Entity("HotelAdoNet.Reserva", b =>
                {
                    b.Navigation("Quartos");
                });

            modelBuilder.Entity("HotelAdoNet.Tipologia", b =>
                {
                    b.Navigation("Quartos");
                });
#pragma warning restore 612, 618
        }
    }
}
